### ISSUE TITLE
Error: No u-he synths detected. Exiting.

### ISSUE THREAD

**Issue by Cris--** [Fannon/u-he-preset-randomizer#4]
Hi,

i tried it with my Diva installation with custom path.
`C:\Audio\Plugin Installationen\u-he\Diva.data`

I edited the _detector.ts_ to:
```
  // Otherwise try Windows or Linux file system conventions
  const locationsToTry = [
    // Windows locations
    
    path.join(os.homedir(),`/Documents/u-he/__SynthName__.data/`),
    `C:/Audio/Plugin Installationen/u-he/__SynthName__.data/`,

```

But still gettin the error.
u-he Preset Randomizer CLI v1.0.2

[detector.ts.txt](https://github.com/Fannon/u-he-preset-randomizer/files/15497382/detector.ts.txt)

**Comment by Fannon** [comment]
Hi @Cris-- ,

thanks for trying out a fix already!

I assume your folder is `C:/Audio/Plugin Installationen/u-he/`?

Once you made the change, you need either to build the tool via `npm run build` or you use `tsx src/cli.ts` to do the build/transpilation right along. 

I wonder how the u-he synths know where the custom installation directory is. Ideally, this could be picked up as well.

**Comment by Fannon** [comment]
Another idea: I could add a CLI parameter so you could pass your custom path. E.g. like:

```sh
npx u-he-preset-randomizer@latest --custom-folder "C:/Audio/Plugin Installationen/u-he/"
```

**Comment by Fannon** [comment]
Ok, I've just releases v1.0.3 which now supports the `--custom-folder` option. Could you try that @Cris-- ? 
It would be great if you can verify if this works or not.

This should do the trick:
```sh
npx u-he-preset-randomizer@1.0.3 --custom-folder "C:/Audio/Plugin Installationen/u-he/"
```

**Comment by Cris--** [comment]
*.data folders are now founded but..

Not working by _Randomize existing preset_ with all options.

```
D:\Download>npx u-he-preset-randomizer@1.0.3 --custom-folder "C:/Audio/Plugin Installationen/u-he/"
======================================================================
u-he Preset Randomizer CLI v1.0.3
======================================================================
Documentation: https://github.com/Fannon/u-he-preset-randomizer#readme

? Which u-he synth to generate presets for? Diva
? Which random mode? Randomize existing preset
? Which modifiers or selectors (multi-choice)?
> Loading and analyzing preset library...
> Loading preset library for Diva in C:/Audio/Plugin Installationen/u-he/ with pattern "undefined"
Could not find presets with glob pattern: **/* in library: C:\Audio\Plugin Installationen\u-he\Presets\Diva
Could not find presets with glob pattern: **/* in user library: C:\Audio\Plugin Installationen\u-he\UserPresets\Diva
Error: No presets found with glob pattern: **/* inC:\Audio\Plugin Installationen\u-he\Presets\Diva
```

Update: checked also now with 1.0.4

`npx u-he-preset-randomizer@1.0.4 --custom-folder "C:/Audio/Plugin Installationen/u-he/"`

**Comment by Cris--** [comment]
Seems path `Diva.data\` is missing:

wrong:
`C:\Audio\Plugin Installationen\u-he\Presets\Diva`

correct:
`C:\Audio\Plugin Installationen\u-he\Diva.data\Presets\Diva`

**Comment by Fannon** [comment]
Let me check this today evening. Actually it should add the Diva.data by itself. 

So this path is existing on your machine and it contains the default preset library: `C:\Audio\Plugin Installationen\u-he\Diva.data\Presets\Diva` ?

**Comment by Cris--** [comment]
correct

**Comment by Fannon** [comment]
@Cris--  Ok, I only had a few minutes but quickly tried out something. Can you try again with v1.0.6?

I may write you in Discord directly if it doesn't work out.
